apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
      - name: python-http-server
        image: python:2.7
        command: ["/bin/bash"]
        args: ["-c", "echo \" Hello from $(hostname)\" > index.html; python -m SimpleHTTPServer 8888"]
        ports:
        - name: http
          containerPort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: test-service
  namespace: test-deployment
spec:
  selector:
    app: test-pod
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 8888