releases:
- name: nginx-ingress
  namespace: nginx-ingress
  chart: ingress-nginx/ingress-nginx
  version: 3.23.0
  values:
  - ./nginx-ingress.yaml
  - ./daemonset.yaml
  - ./cloud.yml
  - fullnameOverride: nginx-ingress
