serviceAccount:
  create: true

rbac:
  create: true

podSecurityPolicy:
  enabled: true

controller:
  ingressClass: nginx
  priorityClassName: addons-critical

  extraArgs:
    enable-ssl-passthrough: ""
  config: # See: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
    ssl-session-timeout: 2h
    # http://nginx.org/en/docs/http/ngx_http_gzip_module.html
    use-gzip: 'true'
    gzip-level: '5'   # 1-9
    # https://github.com/google/ngx_brotli#configuration-directives
    enable-brotli: 'true'
    brotli-level: '6' # 0-11
    log-format-escape-json: "true"
    log-format-upstream: '{"time": "$time_iso8601","request_scheme": "$scheme","remote_addr": "$remote_addr","remote_user": "$remote_user","body_bytes_sent": "$body_bytes_sent", "request_time": "$request_time", "status": "$status", "request": "$request", "request_method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent", "http_x_forwarded_for": "$http_x_forwarded_for", "http_host": "$http_host", "upstream_addr": "$upstream_addr", "upstream_response_time": "$upstream_response_time", "upstream_cache_status": "$upstream_cache_status", "log_type": "nginx_access", "connection": "$connection", "connection_requests": "$connection_requests"}'

  admissionWebhooks:
    enabled: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: false
      rules: [] # TODO

defaultBackend:
  enabled: true
