releases:
- name: prometheus
  namespace: observability-system
  chart: prometheus-community/kube-prometheus-stack
  version: 16.1.1
  values:
  - ./operator+deps.yaml
  - ./prometheus.yaml
  - ./scraping.yaml
  - ./alertmanager.yaml
  - fullnameOverride: promops
  - prometheus-node-exporter:
      fullnameOverride: prometheus-node-exporter
  - kube-state-metrics:
      fullnameOverride: kube-state-metrics
  
- name: pushgateway
  namespace: observability-system
  chart: prometheus-community/prometheus-pushgateway
  version: 1.7.0
  values:
  - ./pushgateway.yaml
  - fullnameOverride: pushgateway