server:
    address: 0.0.0.0
    port: 8088
management:
    endpoints:
        web:
            exposure:
                include: "*"
logging:
    config: file:${workdir:.}/config/log4j2.xml
spring:
    rabbitmq:
        host: 10.22.7.88
        port: 6789
        username: qrcode
        password: qrcode
        requested-heartbeat: 45
        virtual-host: qrcode
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@10.22.7.63:1521/GTGT
        username: MMS
        password: mms
        hikari:
            connection-timeout: 20000
            minimum-idle: 5
            maximum-pool-size: 10
            idle-timeout: 10000
            max-lifetime: 1000
    jpa:
        show-sql: true
    redis:
        database: 3
        password: testredis@123
        sentinel:
            master: redismaster
            nodes:
                - 10.22.7.111:26379
                - 10.22.7.112:26379
        jedis:
            pool:
                max-idle: 10
                max-active: 20
                max-wait: 100
                min-idle: 5